POST http://localhost:8081/project
Content-Type: application/json

{
  "name": "SpaceX"
}

###

GET http://localhost:8081/project/1

###

POST http://localhost:8081/employee
Content-Type: application/json

{
  "firstName": "Katarzyna",
  "lastName": "Dieta",
  "city": "Szczecin",
  "projectId": "1"
}

###

GET http://localhost:8081/employee

###