POST http://localhost:8080/project
Content-Type: application/json
Cookie: {{sessionId}}

{
  "name": "SpaceX"
}

###

GET http://localhost:8080/project/1
Cookie: {{sessionId}}

###

POST http://localhost:8080/employee
Content-Type: application/json
Cookie: {{sessionId}}

{
  "firstName": "Katarzyna",
  "lastName": "Dieta",
  "city": "Szczecin",
  "projectId": "1"
}

###

GET http://localhost:8080/employee
Cookie: {{sessionId}}

###